x-services:
  fastapi_app: &fastapi_app
    networks:
      - webnet
      - postgresnet
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        FASTAPI_ENV: "development"
    volumes:
      - .:/app
    env_file:
      - ./config/.env


version: "3.8"
services:
  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgresnet
    env_file:
    - ./config/.env
    ports:
      - "5432:5432"

  web:
    <<: *fastapi_app
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - db

networks:
  postgresnet:
  webnet:

volumes:
  pgdata:
